[phases.setup]
nixPkgs = ["openssl", "openssl.dev"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["DATABASE_URL=postgresql://x:x@localhost:5432/x npx prisma generate"]

[start]
cmd = "npm start"
